name: CI test workflow
on:
  push:
    branches:
      - "main"
    paths:
      - "own_folder/**"
      - ".github/workflows/dev-ci.yaml"

  workflow_dispatch:

jobs:
  dev-ci:
    runs-on: Ubuntu-latest

    defaults:
      run:
        working-directory: ./own_folder

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Unit test example
        run: pytest -V test_sample.py
